### ISSUE TITLE
double homebrew linking

### ISSUE THREAD

**Issue by Ken-B** [lobingera/Rsvg.jl#29]
I cannot use both Gadfly and VegaLite for plotting because of a strange issue that I think comes from `Rsvg.jl`, but it's maybe also related to `Homebrew.jl` (@staticfloat)?

The installation runs fine (I tried reinstalling everything, from scratch, checkout master etc.), but testing `Rsvg.jl` always gives the following error:

    objc[47481]: Class GNotificationCenterDelegate is implemented in both /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x111399498) and /Users/ken/.julia/packages/Homebrew/s09IX/deps/usr/lib/libgio-2.0.dylib (0x129254498). One of the two will be used. Which one is undefined.

I tried linking inside julia package folders manually to system `libgio` (installed through brew on my system), but although the errors go away, the plots are all scrambled.

Any help appreciated, thanks!

<details>
<summary>Full output</summary>

```
(v1.0) pkg> test Rsvg
   Testing Rsvg
    Status `/var/folders/h9/8wp6_1kx6_v6wm7_vy5w_pbm0000gn/T/tmp1eCjdp/Manifest.toml`
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.3
  [e1450e63] BufferedStreams v1.0.0
  [159f3aea] Cairo v0.5.6
  [3da002f7] ColorTypes v0.7.5
  [5ae59095] Colors v0.9.5
  [34da2185] Compat v1.5.1
  [53c48c17] FixedPointNumbers v0.5.3
  [a2bd30eb] Graphics v0.4.0
  [0862f596] HTTPClient v0.2.1
  [d9be37ee] Homebrew v0.7.1
  [682c06a0] JSON v0.20.0
  [b27032c2] LibCURL v0.4.1
  [522f3ed2] LibExpat v0.5.0
  [2ec943e9] Libz v1.0.0
  [77ba4419] NaNMath v0.3.2
  [189a3867] Reexport v0.2.0
  [c4c386cf] Rsvg v0.2.3+ #master (https://github.com/lobingera/Rsvg.jl.git)
  [30578b45] URIParser v0.4.0
  [c17dfb99] WinRPM v0.4.2
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
Test Summary:                | Pass  Total
dimensions of known images   |    8      8
Test Summary:                | Pass  Total
render to png                |    4      4
objc[47481]: Class GNotificationCenterDelegate is implemented in both /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x111399498) and /Users/ken/.julia/packages/Homebrew/s09IX/deps/usr/lib/libgio-2.0.dylib (0x129254498). One of the two will be used. Which one is undefined.

(process:47481): librsvg-CRITICAL **: 22:12:27.907: rsvg_handle_new_from_stream_sync: assertion 'G_IS_INPUT_STREAM (input_stream)' failed

signal (11): Segmentation fault: 11
in expression starting at /Users/ken/.julia/packages/Rsvg/uwc9D/test/runtests.jl:60
getproperty at ./sysimg.jl:18 [inlined]
getindex at ./refvalue.jl:32 [inlined]
handle_new_from_data at /Users/ken/.julia/packages/Rsvg/uwc9D/src/calls.jl:109
test_render_string_to_png at /Users/ken/.julia/packages/Rsvg/uwc9D/test/test.jl:52
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
test_render_string_to_png at /Users/ken/.julia/packages/Rsvg/uwc9D/test/test.jl:49
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
macro expansion at /Users/ken/.julia/packages/Rsvg/uwc9D/test/runtests.jl:63 [inlined]
macro expansion at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
top-level scope at /Users/ken/.julia/packages/Rsvg/uwc9D/test/runtests.jl:62
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:799
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:838
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:839 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:846
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1044
include at ./sysimg.jl:29
include at ./client.jl:392
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:682
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:806
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x10a72fc0f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:815
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:805
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:754
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:622
eval at ./boot.jl:319
exec_options at ./client.jl:243
_start at ./client.jl:425
true_main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)
Allocations: 5877126 (Pool: 5876152; Big: 974); GC: 12
ERROR: Package Rsvg errored during testing

julia> versioninfo(verbose=true)
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  uname: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz:
              speed         user         nice          sys         idle          irq
       #1  2800 MHz      83706 s          0 s      68444 s     577018 s          0 s
       #2  2800 MHz       4185 s          0 s       3715 s     721189 s          0 s
       #3  2800 MHz      88050 s          0 s      35528 s     605526 s          0 s
       #4  2800 MHz       4511 s          0 s       3665 s     720909 s          0 s
       #5  2800 MHz      74952 s          0 s      25474 s     628670 s          0 s
       #6  2800 MHz       4765 s          0 s       3308 s     721009 s          0 s
       #7  2800 MHz      63477 s          0 s      19159 s     646455 s          0 s
       #8  2800 MHz       4920 s          0 s       2895 s     721264 s          0 s

  Memory: 16.0 GB (441.94921875 MB free)
  Uptime: 258904.0 sec
  Load Avg:  1.4580078125  1.60009765625  1.673828125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  XPC_FLAGS = 0x0
  PATH = /usr/local/sbin:/Users/ken/anaconda3/bin:/Users/ken/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
  TERM = xterm-256color
  HOME = /Users/ken

julia>
```

</details>

**Comment by Ken-B** [comment]
@lobingera bump. Any idea?

**Comment by lobingera** [comment]
Not really. I was a little bit hoping @staticfloat can give us some background on problems like this. 
In general i see this as problem to be solved by the binary providers (BinDeps, Homebrew) and not on the package side. When we build in the call to libgio to enable RSVG to read files longer than 10MBytes i was putting a comment on having libgio as package to avoid issues with the dependency tree.

**Comment by staticfloat** [comment]
I think to solve this, you need to figure out what in your dependency chain is loading in from `/usr/local/`.  Ideally, nothing would be loading from outside of `~/.julia`, and then we would have full control over all the versions being used.

**Comment by Ken-B** [comment]
I've found that `Homebrew.brew(`reinstall glib`)` makes the testing error disappear. But the plots with Gadfly still look wrong (too many ticks on axis) and VegaLite just crashes my IJulia kernel. 

Good suggestion, @staticfloat. Any pointers on how to do that in Julia? I now see I got some weird error in VegaLite.jl, but somehow (?) its tests pass:
```
#other packages omitted
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
/Users/ken/.julia/packages/VegaLite/Sl5pu/deps/node_modules/vega-lite/build/vega-lite.js:3959
      throw new Error(message.INVALID_SPEC);
      ^

Error: Invalid spec
    at normalize$2 (/Users/ken/.julia/packages/VegaLite/Sl5pu/deps/node_modules/vega-lite/build/vega-lite.js:3959:13)
    at Object.compile (/Users/ken/.julia/packages/VegaLite/Sl5pu/deps/node_modules/vega-lite/build/vega-lite.js:12876:22)
    at compile (/Users/ken/.julia/packages/VegaLite/Sl5pu/src/rendering/compilesvg.js:21:20)
    at /Users/ken/.julia/packages/VegaLite/Sl5pu/src/rendering/compilesvg.js:17:3
    at Socket.<anonymous> (/Users/ken/.julia/packages/VegaLite/Sl5pu/deps/node_modules/rw/lib/rw/read-file.js:22:33)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Test Summary: | Pass  Total
VegaLite      |  101    101
   Testing VegaLite tests passed
```
So maybe node.js is somehow linking to `/usr/local/`?

Anyway, this seems not to be an issue anymore with this package, so feel free to close, but I'm all ears for tips to investigate further. Thanks!
